apiVersion: batch/v1
kind: Job
metadata:
  name: free-service-job
spec:
  parallelism: 2  # Set the number of parallel pods for the job
  template:
    spec:
      containers:
      - name: free-classifier-container
        image: jjyyjay/classifier-image
        resources:
          limits:
            cpu: "0.9"  # Set the CPU limit to 0.9
          requests:
            cpu: "0.9"  # Set the CPU request to 0.9
        env:
        - name: DATASET
          value: mnist
        - name: TYPE
          value: ff
      restartPolicy: OnFailure